- hosts: all
  vars_files: 
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  tasks:
    - name: install webserver software
      package:
        name: "{{ package_name }}"
        state: latest

    - name: copy webpage
      template:
        src: task14.html.j2
        dest: "{{ doc_root }}/task14_3.html"

    - name: Start Web server service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
